export const products1 = [
     {
       id: '1000',
       code: 'f230fh0g3',
       name: 'Bamboo Watch',
       description: 'Elegant bamboo watch with minimalistic design.',
       image: 'bamboo-watch.jpg',
       price: 65,
       category: 'Accessories',
       quantity: 24,
       inventoryStatus: 'INSTOCK',
       rating: 5
     },
     {
       id: '1001',
       code: 'nvklal433',
       name: 'Black Leather Shoes',
       description: 'Premium black leather shoes for formal occasions.',
       image: 'black-leather-shoes.jpg',
       price: 120,
       category: 'Footwear',
       quantity: 15,
       inventoryStatus: 'LOWSTOCK',
       rating: 4
     },
     {
       id: '1002',
       code: 'zz21cz3c1',
       name: 'Silver Necklace',
       description: 'Stylish silver necklace with a pendant.',
       image: 'silver-necklace.jpg',
       price: 45,
       category: 'Jewelry',
       quantity: 30,
       inventoryStatus: 'INSTOCK',
       rating: 4
     },
     {
       id: '1003',
       code: '244wgerg2',
       name: 'Running Sneakers',
       description: 'Lightweight running sneakers for everyday use.',
       image: 'running-sneakers.jpg',
       price: 80,
       category: 'Footwear',
       quantity: 20,
       inventoryStatus: 'INSTOCK',
       rating: 5
     },
     {
       id: '1004',
       code: 'h456wer53',
       name: 'Classic Sunglasses',
       description: 'UV-protected classic sunglasses with a retro frame.',
       image: 'classic-sunglasses.jpg',
       price: 35,
       category: 'Accessories',
       quantity: 50,
       inventoryStatus: 'INSTOCK',
       rating: 3
     },
     {
       id: '1005',
       code: 'av2231fwg',
       name: 'Leather Wallet',
       description: 'Genuine leather wallet with multiple compartments.',
       image: 'leather-wallet.jpg',
       price: 40,
       category: 'Accessories',
       quantity: 18,
       inventoryStatus: 'LOWSTOCK',
       rating: 4
     },
     {
       id: '1006',
       code: 'cdscsd231',
       name: 'Digital Watch',
       description: 'Water-resistant digital watch with alarm feature.',
       image: 'digital-watch.jpg',
       price: 55,
       category: 'Accessories',
       quantity: 22,
       inventoryStatus: 'INSTOCK',
       rating: 4
     },
     {
       id: '1007',
       code: 'qw23qew23',
       name: 'Sports Cap',
       description: 'Breathable sports cap with adjustable strap.',
       image: 'sports-cap.jpg',
       price: 25,
       category: 'Apparel',
       quantity: 40,
       inventoryStatus: 'INSTOCK',
       rating: 5
     },
     {
       id: '1008',
       code: 'er3345rew',
       name: 'Fitness Tracker',
       description: 'Advanced fitness tracker with heart rate monitor.',
       image: 'fitness-tracker.jpg',
       price: 95,
       category: 'Electronics',
       quantity: 10,
       inventoryStatus: 'LOWSTOCK',
       rating: 5
     },
     {
       id: '1009',
       code: 'tyu67889',
       name: 'Casual T-Shirt',
       description: 'Comfortable cotton casual t-shirt available in multiple colors.',
       image: 'casual-tshirt.jpg',
       price: 20,
       category: 'Apparel',
       quantity: 60,
       inventoryStatus: 'INSTOCK',
       rating: 3
     },
     {
      id: '1000',
      code: 'f230fh0g3',
      name: 'Bamboo Watch',
      description: 'Elegant bamboo watch with minimalistic design.',
      image: 'bamboo-watch.jpg',
      price: 65,
      category: 'Accessories',
      quantity: 24,
      inventoryStatus: 'INSTOCK',
      rating: 5
    },
    {
      id: '1001',
      code: 'nvklal433',
      name: 'Black Leather Shoes',
      description: 'Premium black leather shoes for formal occasions.',
      image: 'black-leather-shoes.jpg',
      price: 120,
      category: 'Footwear',
      quantity: 15,
      inventoryStatus: 'LOWSTOCK',
      rating: 4
    },
    {
      id: '1002',
      code: 'zz21cz3c1',
      name: 'Silver Necklace',
      description: 'Stylish silver necklace with a pendant.',
      image: 'silver-necklace.jpg',
      price: 45,
      category: 'Jewelry',
      quantity: 30,
      inventoryStatus: 'INSTOCK',
      rating: 4
    },
    {
      id: '1003',
      code: '244wgerg2',
      name: 'Running Sneakers',
      description: 'Lightweight running sneakers for everyday use.',
      image: 'running-sneakers.jpg',
      price: 80,
      category: 'Footwear',
      quantity: 20,
      inventoryStatus: 'INSTOCK',
      rating: 5
    },
    {
      id: '1004',
      code: 'h456wer53',
      name: 'Classic Sunglasses',
      description: 'UV-protected classic sunglasses with a retro frame.',
      image: 'classic-sunglasses.jpg',
      price: 35,
      category: 'Accessories',
      quantity: 50,
      inventoryStatus: 'INSTOCK',
      rating: 3
    },
    {
      id: '1005',
      code: 'av2231fwg',
      name: 'Leather Wallet',
      description: 'Genuine leather wallet with multiple compartments.',
      image: 'leather-wallet.jpg',
      price: 40,
      category: 'Accessories',
      quantity: 18,
      inventoryStatus: 'LOWSTOCK',
      rating: 4
    },
    {
      id: '1006',
      code: 'cdscsd231',
      name: 'Digital Watch',
      description: 'Water-resistant digital watch with alarm feature.',
      image: 'digital-watch.jpg',
      price: 55,
      category: 'Accessories',
      quantity: 22,
      inventoryStatus: 'INSTOCK',
      rating: 4
    },
    {
      id: '1007',
      code: 'qw23qew23',
      name: 'Sports Cap',
      description: 'Breathable sports cap with adjustable strap.',
      image: 'sports-cap.jpg',
      price: 25,
      category: 'Apparel',
      quantity: 40,
      inventoryStatus: 'INSTOCK',
      rating: 5
    },
    {
      id: '1008',
      code: 'er3345rew',
      name: 'Fitness Tracker',
      description: 'Advanced fitness tracker with heart rate monitor.',
      image: 'fitness-tracker.jpg',
      price: 95,
      category: 'Electronics',
      quantity: 10,
      inventoryStatus: 'LOWSTOCK',
      rating: 5
    },
    {
      id: '1009',
      code: 'tyu67889',
      name: 'Casual T-Shirt',
      description: 'Comfortable cotton casual t-shirt available in multiple colors.',
      image: 'casual-tshirt.jpg',
      price: 20,
      category: 'Apparel',
      quantity: 60,
      inventoryStatus: 'INSTOCK',
      rating: 3
    },
    {
      id: '1000',
      code: 'f230fh0g3',
      name: 'Bamboo Watch',
      description: 'Elegant bamboo watch with minimalistic design.',
      image: 'bamboo-watch.jpg',
      price: 65,
      category: 'Accessories',
      quantity: 24,
      inventoryStatus: 'INSTOCK',
      rating: 5
    },
    {
      id: '1001',
      code: 'nvklal433',
      name: 'Black Leather Shoes',
      description: 'Premium black leather shoes for formal occasions.',
      image: 'black-leather-shoes.jpg',
      price: 120,
      category: 'Footwear',
      quantity: 15,
      inventoryStatus: 'LOWSTOCK',
      rating: 4
    },
    {
      id: '1002',
      code: 'zz21cz3c1',
      name: 'Silver Necklace',
      description: 'Stylish silver necklace with a pendant.',
      image: 'silver-necklace.jpg',
      price: 45,
      category: 'Jewelry',
      quantity: 30,
      inventoryStatus: 'INSTOCK',
      rating: 4
    },
    {
      id: '1003',
      code: '244wgerg2',
      name: 'Running Sneakers',
      description: 'Lightweight running sneakers for everyday use.',
      image: 'running-sneakers.jpg',
      price: 80,
      category: 'Footwear',
      quantity: 20,
      inventoryStatus: 'INSTOCK',
      rating: 5
    },
    {
      id: '1004',
      code: 'h456wer53',
      name: 'Classic Sunglasses',
      description: 'UV-protected classic sunglasses with a retro frame.',
      image: 'classic-sunglasses.jpg',
      price: 35,
      category: 'Accessories',
      quantity: 50,
      inventoryStatus: 'INSTOCK',
      rating: 3
    },
    {
      id: '1005',
      code: 'av2231fwg',
      name: 'Leather Wallet',
      description: 'Genuine leather wallet with multiple compartments.',
      image: 'leather-wallet.jpg',
      price: 40,
      category: 'Accessories',
      quantity: 18,
      inventoryStatus: 'LOWSTOCK',
      rating: 4
    },
    {
      id: '1006',
      code: 'cdscsd231',
      name: 'Digital Watch',
      description: 'Water-resistant digital watch with alarm feature.',
      image: 'digital-watch.jpg',
      price: 55,
      category: 'Accessories',
      quantity: 22,
      inventoryStatus: 'INSTOCK',
      rating: 4
    },
    {
      id: '1007',
      code: 'qw23qew23',
      name: 'Sports Cap',
      description: 'Breathable sports cap with adjustable strap.',
      image: 'sports-cap.jpg',
      price: 25,
      category: 'Apparel',
      quantity: 40,
      inventoryStatus: 'INSTOCK',
      rating: 5
    },
    {
      id: '1008',
      code: 'er3345rew',
      name: 'Fitness Tracker',
      description: 'Advanced fitness tracker with heart rate monitor.',
      image: 'fitness-tracker.jpg',
      price: 95,
      category: 'Electronics',
      quantity: 10,
      inventoryStatus: 'LOWSTOCK',
      rating: 5
    },
    {
      id: '1009',
      code: 'tyu67889',
      name: 'Casual T-Shirt',
      description: 'Comfortable cotton casual t-shirt available in multiple colors.',
      image: 'casual-tshirt.jpg',
      price: 20,
      category: 'Apparel',
      quantity: 60,
      inventoryStatus: 'INSTOCK',
      rating: 3
    },
    {
     id: '1000',
     code: 'f230fh0g3',
     name: 'Bamboo Watch',
     description: 'Elegant bamboo watch with minimalistic design.',
     image: 'bamboo-watch.jpg',
     price: 65,
     category: 'Accessories',
     quantity: 24,
     inventoryStatus: 'INSTOCK',
     rating: 5
   },
   {
     id: '1001',
     code: 'nvklal433',
     name: 'Black Leather Shoes',
     description: 'Premium black leather shoes for formal occasions.',
     image: 'black-leather-shoes.jpg',
     price: 120,
     category: 'Footwear',
     quantity: 15,
     inventoryStatus: 'LOWSTOCK',
     rating: 4
   },
   {
     id: '1002',
     code: 'zz21cz3c1',
     name: 'Silver Necklace',
     description: 'Stylish silver necklace with a pendant.',
     image: 'silver-necklace.jpg',
     price: 45,
     category: 'Jewelry',
     quantity: 30,
     inventoryStatus: 'INSTOCK',
     rating: 4
   },
   {
     id: '1003',
     code: '244wgerg2',
     name: 'Running Sneakers',
     description: 'Lightweight running sneakers for everyday use.',
     image: 'running-sneakers.jpg',
     price: 80,
     category: 'Footwear',
     quantity: 20,
     inventoryStatus: 'INSTOCK',
     rating: 5
   },
   {
     id: '1004',
     code: 'h456wer53',
     name: 'Classic Sunglasses',
     description: 'UV-protected classic sunglasses with a retro frame.',
     image: 'classic-sunglasses.jpg',
     price: 35,
     category: 'Accessories',
     quantity: 50,
     inventoryStatus: 'INSTOCK',
     rating: 3
   },
   {
     id: '1005',
     code: 'av2231fwg',
     name: 'Leather Wallet',
     description: 'Genuine leather wallet with multiple compartments.',
     image: 'leather-wallet.jpg',
     price: 40,
     category: 'Accessories',
     quantity: 18,
     inventoryStatus: 'LOWSTOCK',
     rating: 4
   },
   {
     id: '1006',
     code: 'cdscsd231',
     name: 'Digital Watch',
     description: 'Water-resistant digital watch with alarm feature.',
     image: 'digital-watch.jpg',
     price: 55,
     category: 'Accessories',
     quantity: 22,
     inventoryStatus: 'INSTOCK',
     rating: 4
   },
   {
     id: '1007',
     code: 'qw23qew23',
     name: 'Sports Cap',
     description: 'Breathable sports cap with adjustable strap.',
     image: 'sports-cap.jpg',
     price: 25,
     category: 'Apparel',
     quantity: 40,
     inventoryStatus: 'INSTOCK',
     rating: 5
   },
   {
     id: '1008',
     code: 'er3345rew',
     name: 'Fitness Tracker',
     description: 'Advanced fitness tracker with heart rate monitor.',
     image: 'fitness-tracker.jpg',
     price: 95,
     category: 'Electronics',
     quantity: 10,
     inventoryStatus: 'LOWSTOCK',
     rating: 5
   },
   {
     id: '1009',
     code: 'tyu67889',
     name: 'Casual T-Shirt',
     description: 'Comfortable cotton casual t-shirt available in multiple colors.',
     image: 'casual-tshirt.jpg',
     price: 20,
     category: 'Apparel',
     quantity: 60,
     inventoryStatus: 'INSTOCK',
     rating: 3
   }
];
   